export const themes = {
    ai: {
        color: 'white',
        background: 'black',
        textColor: 'black',
        textBackground: 'white',
    },
    default: {
        color: 'black',
        background: 'white',
        textColor: 'black',
        textBackground: 'white',
    },
    maths: {
        color: 'black',
        background: '#ffdb23',
        textColor: 'black',
        textBackground: 'white',
    },
    social: {
        color: 'black',
        background: '#eff425',
        textColor: 'black',
        textBackground: '#F9F9F9',
    },
    gray: {
        color: 'black',
        background: 'white',
        textColor: 'black',
        textBackground: '#e9e2e2',
    },
    rust: {
        color: 'black',
        background: '#f5a142',
        textColor: 'black',
        textBackground: 'white',
    },
    pink: {
        color: 'black',
        background: '#ffbad7',
        textColor: 'black',
        textBackground: '#ffbad7',
        full: true,
    },
    chill_black: {
        color: 'white',
        background: '#1a1c22',
        textColor: 'black',
        textBackground: 'white',
    },
    green: {
        color: 'black',
        background: '#a1ff00',
        textColor: 'black',
        textBackground: 'white',
    },
    light_blue_full: {
        color: 'black',
        background: '#99ffff',
        textColor: 'black',
        textBackground: '#99ffff',
        full: true,
    },
    purple: {
        color: 'black',
        background: '#ffa9f7',
        textColor: 'black',
        textBackground: 'white',
    },
};
